name: Build Flutter APK & AAB

on:
  push:
    branches: [ "main" ]

env:
  APP_DIR: .

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show layout
        run: |
          pwd
          ls -la
          test -f pubspec.yaml || (echo "pubspec.yaml introuvable" && exit 1)
          grep -E '^name:' pubspec.yaml || true
          grep -E '^environment:' -n -A 2 pubspec.yaml || true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter 3.16.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Regenerate platform folders
        run: flutter create . --project-name bbb_locations

      - name: Build APK
        run: flutter build apk

      - name: Build AAB
        run: flutter build appbundle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ env.APP_DIR }}/build/app/outputs/flutter-apk/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: ${{ env.APP_DIR }}/build/app/outputs/bundle/release/*.aab
